module TestWellKnownTypes

include("setup.jl")

# Phase 7: well-known types under `ProtoBufDescriptors.google.protobuf.*`,
# generated by our own codegen via `gen/regen_wkt.jl`. This phase ships
# the seven dependency-free WKTs:
#
#   any, duration, empty, field_mask, source_context, timestamp, wrappers
#
# The other four — api, type, struct — are deferred until cross-file
# imports (api/type) and recursion (struct.proto's Value↔ListValue cycle)
# are added to codegen.

const WKT = ProtoBufDescriptors.google.protobuf

function rt(x::T) where {T}
    io = IOBuffer()
    Base.invokelatest(ProtoBufDescriptors.encode,
        ProtoBufDescriptors.ProtoEncoder(io), x)
    bytes = take!(io)
    decoded = Base.invokelatest(ProtoBufDescriptors.decode,
        ProtoBufDescriptors.ProtoDecoder(IOBuffer(bytes)), T)
    return decoded, bytes
end

@testset "Phase 7 — well-known types (round-trip)" begin
    @testset "Timestamp" begin
        # epoch + 1.7e9 sec, 123_456_789 nanos. Field 1 = seconds (varint),
        # field 2 = nanos (varint). protoc emits in field-number order.
        t = Base.invokelatest(WKT.Timestamp, Int64(1_700_000_000), Int32(123_456_789))
        decoded, bytes = rt(t)
        @test decoded.seconds == t.seconds
        @test decoded.nanos == t.nanos
        # Hand-verified wire bytes: tag=0x08 + varint(1_700_000_000) [5B]
        # + tag=0x10 + varint(123_456_789) [4B] = 11 bytes total.
        @test length(bytes) == 11
    end

    @testset "Timestamp epoch" begin
        # All-zero Timestamp encodes to zero bytes (proto3 implicit
        # presence: zero is indistinguishable from unset).
        t = Base.invokelatest(WKT.Timestamp, Int64(0), Int32(0))
        decoded, bytes = rt(t)
        @test decoded.seconds == 0 && decoded.nanos == 0
        @test isempty(bytes)
    end

    @testset "Duration" begin
        d = Base.invokelatest(WKT.Duration, Int64(-3600), Int32(-500_000_000))
        decoded, bytes = rt(d)
        @test decoded.seconds == d.seconds
        @test decoded.nanos == d.nanos
        # Negative int32/int64 encode as 10-byte sign-extended varint, so
        # tag=0x08 + 10B + tag=0x10 + 10B = 22 bytes. Our codec's Int32
        # encode already does this correctly (encode.jl:73).
        @test length(bytes) == 22
    end

    @testset "Empty" begin
        e = Base.invokelatest(WKT.Empty)
        decoded, bytes = rt(e)
        @test decoded isa WKT.Empty
        @test isempty(bytes)
    end

    @testset "FieldMask" begin
        # paths is `repeated string` — proto3 repeated, but strings are
        # length-delimited per element regardless of packed/unpacked.
        m = Base.invokelatest(WKT.FieldMask, ["foo", "bar.baz", "qux"])
        decoded, bytes = rt(m)
        @test decoded.paths == m.paths
        @test !isempty(bytes)
    end

    @testset "SourceContext" begin
        s = Base.invokelatest(WKT.SourceContext, "/path/to/file.proto")
        decoded, _ = rt(s)
        @test decoded.file_name == s.file_name
    end

    @testset "Any" begin
        # Any holds an opaque message in `value::Bytes`, identified by a
        # type URL. The package doesn't unmarshal — that's a v1
        # limitation. Just round-trip the wrapper.
        a = Base.invokelatest(WKT.Any,
            "type.googleapis.com/google.protobuf.Timestamp",
            UInt8[0x08, 0xC0, 0x84, 0x3D])  # seconds=1_000_000 in varint
        decoded, _ = rt(a)
        @test decoded.type_url == a.type_url
        @test decoded.value == a.value
    end

    @testset "Wrappers — every variant" begin
        wrappers = [
            (WKT.DoubleValue, 3.14),
            (WKT.FloatValue, 3.14f0),
            (WKT.Int32Value, Int32(-42)),
            (WKT.Int64Value, Int64(-42_000_000_000)),
            (WKT.UInt32Value, UInt32(0xFFFFFFFF)),
            (WKT.UInt64Value, UInt64(0xFFFFFFFFFFFFFFFF)),
            (WKT.BoolValue, true),
            (WKT.StringValue, "héllo"),
            (WKT.BytesValue, UInt8[0x00, 0xFF, 0xAB]),
        ]
        for (T, v) in wrappers
            w = Base.invokelatest(T, v)
            decoded, _ = rt(w)
            @test decoded.value == w.value
        end
    end
end

end  # module TestWellKnownTypes
