# Generated by ProtocGen. Do not edit.
# source: library.proto (proto3 syntax)
#! format: off

import ProtocGen as PB
using ProtocGen: OneOf, OrderedDict
using ProtocGen: encode, decode, encode_json, decode_json
using ProtocGen.EnumX: @enumx
using ProtocGen.StructHelpers: @batteries, @enumbatteries

export Membership, Library, Book, Member

"Subscription tier of a member."
@enumx Membership UNSPECIFIED=0 BASIC=1 PREMIUM=2
"No tier selected." Membership.UNSPECIFIED
"Standard borrowing limits." Membership.BASIC
"Extended limits and early access." Membership.PREMIUM
@enumbatteries Membership.T typesalt=0x8ef4208538c544ba
PB._enum_proto_prefix(::Type{Membership.T}) = "MEMBERSHIP_"

"""
The genre a book belongs to.

Used for shelving and search filters.
"""
@enumx var"Book.Genre" UNSPECIFIED=0 FICTION=1 NONFICTION=2
"Genre was never set (proto3 zero value)." var"Book.Genre".UNSPECIFIED
"Made-up stories." var"Book.Genre".FICTION
"Factual works." var"Book.Genre".NONFICTION
@enumbatteries var"Book.Genre".T typesalt=0x7f1943791a07523a
PB._enum_proto_prefix(::Type{var"Book.Genre".T}) = "GENRE_"

"""
A single book in the catalog.

# Fields
- `isbn::String`: International Standard Book Number, 13-digit form.
- `title::String`: Full title as printed on the cover.
- `genre::var"Book.Genre".T`: Primary genre of the book.
- `availability::Union{Nothing,OneOf{<:Union{Int32,String}}}`: How the book can currently be obtained.
  - `copies_on_shelf::Int32`: Number of physical copies on the shelf.
  - `ebook_url::String`: URL to the e-book, if this is a digital-only title.
"""
struct Book <: PB.AbstractProtoBufMessage
    "International Standard Book Number, 13-digit form."
    isbn::String
    "Full title as printed on the cover."
    title::String
    "Primary genre of the book."
    genre::var"Book.Genre".T
    """
    How the book can currently be obtained.
    - copies_on_shelf::Int32: Number of physical copies on the shelf.
    - ebook_url::String: URL to the e-book, if this is a digital-only title.
    """
    availability::Union{Nothing,OneOf{<:Union{Int32,String}}}
    var"#unknown_fields"::Vector{UInt8}
end
function PB.field_numbers(::Type{Book})
    return (;isbn = 1, title = 2, genre = 3, copies_on_shelf = 4, ebook_url = 5)
end
function PB.json_field_names(::Type{Book})
    return (;isbn = "isbn", title = "title", genre = "genre", copies_on_shelf = "copiesOnShelf", ebook_url = "ebookUrl")
end
PB.register_message_type("library.Book", Book)
function PB.oneof_field_types(::Type{Book})
    return (;availability = (;copies_on_shelf = Int32, ebook_url = String))
end

function PB._decode(_d::PB.AbstractProtoDecoder, ::Type{<:Book}, _endpos::Int=0, _group::Bool=false)
    isbn = ""
    title = ""
    genre = var"Book.Genre".UNSPECIFIED
    availability::Union{Nothing,OneOf{<:Union{Int32,String}}} = nothing
    _unknown_fields = UInt8[]
    while !PB.message_done(_d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(_d)
        if field_number == 1
            isbn = PB._decode(_d, String)
        elseif field_number == 2
            title = PB._decode(_d, String)
        elseif field_number == 3
            genre = PB._decode(_d, var"Book.Genre".T)
        elseif field_number == 4
            availability = OneOf(:copies_on_shelf, PB._decode(_d, Int32))
        elseif field_number == 5
            availability = OneOf(:ebook_url, PB._decode(_d, String))
        else
            PB._skip_and_capture!(_unknown_fields, _d, field_number, wire_type)
        end
    end
    return Book(isbn, title, genre, availability, _unknown_fields)
end

function PB._encode(_e::PB.AbstractProtoEncoder, _x::Book)
    initpos = position(_e.io)
    !isempty(_x.isbn) && PB._encode(_e, 1, _x.isbn)
    !isempty(_x.title) && PB._encode(_e, 2, _x.title)
    _x.genre != var"Book.Genre".UNSPECIFIED && PB._encode(_e, 3, _x.genre)
    let _o = _x.availability
        if !isnothing(_o) && _o.name === :copies_on_shelf
            PB._encode(_e, 4, _o.value)
        end
    end
    let _o = _x.availability
        if !isnothing(_o) && _o.name === :ebook_url
            PB._encode(_e, 5, _o.value)
        end
    end
    if !isempty(_x.var"#unknown_fields")
        write(_e.io, _x.var"#unknown_fields")
    end
    return position(_e.io) - initpos
end
function PB._encoded_size(_x::Book)
    encoded_size = 0
    !isempty(_x.isbn) && (encoded_size += PB._encoded_size(_x.isbn, 1))
    !isempty(_x.title) && (encoded_size += PB._encoded_size(_x.title, 2))
    _x.genre != var"Book.Genre".UNSPECIFIED && (encoded_size += PB._encoded_size(_x.genre, 3))
    let _o = _x.availability
        if !isnothing(_o) && _o.name === :copies_on_shelf
            encoded_size += PB._encoded_size(_o.value, 4)
        end
    end
    let _o = _x.availability
        if !isnothing(_o) && _o.name === :ebook_url
            encoded_size += PB._encoded_size(_o.value, 5)
        end
    end
    encoded_size += length(_x.var"#unknown_fields")
    return encoded_size
end
@batteries Book typesalt=0x91c64d1411f681fb kwconstructor=true kwshow=true
function PB.StructHelpers.default_keywords(::Type{Book})
    return (;isbn = "", title = "", genre = var"Book.Genre".UNSPECIFIED, availability = nothing, var"#unknown_fields" = UInt8[])
end

"""
A person who can borrow books.

# Fields
- `id::String`: Stable unique identifier.
- `name::String`: Display name shown on the membership card.
- `tier::Membership.T`: The member's subscription tier.
"""
struct Member <: PB.AbstractProtoBufMessage
    "Stable unique identifier."
    id::String
    "Display name shown on the membership card."
    name::String
    "The member's subscription tier."
    tier::Membership.T
    var"#unknown_fields"::Vector{UInt8}
end
function PB.field_numbers(::Type{Member})
    return (;id = 1, name = 2, tier = 3)
end
function PB.json_field_names(::Type{Member})
    return (;id = "id", name = "name", tier = "tier")
end
PB.register_message_type("library.Member", Member)

function PB._decode(_d::PB.AbstractProtoDecoder, ::Type{<:Member}, _endpos::Int=0, _group::Bool=false)
    id = ""
    name = ""
    tier = Membership.UNSPECIFIED
    _unknown_fields = UInt8[]
    while !PB.message_done(_d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(_d)
        if field_number == 1
            id = PB._decode(_d, String)
        elseif field_number == 2
            name = PB._decode(_d, String)
        elseif field_number == 3
            tier = PB._decode(_d, Membership.T)
        else
            PB._skip_and_capture!(_unknown_fields, _d, field_number, wire_type)
        end
    end
    return Member(id, name, tier, _unknown_fields)
end

function PB._encode(_e::PB.AbstractProtoEncoder, _x::Member)
    initpos = position(_e.io)
    !isempty(_x.id) && PB._encode(_e, 1, _x.id)
    !isempty(_x.name) && PB._encode(_e, 2, _x.name)
    _x.tier != Membership.UNSPECIFIED && PB._encode(_e, 3, _x.tier)
    if !isempty(_x.var"#unknown_fields")
        write(_e.io, _x.var"#unknown_fields")
    end
    return position(_e.io) - initpos
end
function PB._encoded_size(_x::Member)
    encoded_size = 0
    !isempty(_x.id) && (encoded_size += PB._encoded_size(_x.id, 1))
    !isempty(_x.name) && (encoded_size += PB._encoded_size(_x.name, 2))
    _x.tier != Membership.UNSPECIFIED && (encoded_size += PB._encoded_size(_x.tier, 3))
    encoded_size += length(_x.var"#unknown_fields")
    return encoded_size
end
@batteries Member typesalt=0xd846fa30fc2583c0 kwconstructor=true kwshow=true
function PB.StructHelpers.default_keywords(::Type{Member})
    return (;id = "", name = "", tier = Membership.UNSPECIFIED, var"#unknown_fields" = UInt8[])
end

"""
A library branch: catalogs books and the members who borrow them.

This is the top-level container for the whole system. Leading_detached
comments (separated by a blank line) are dropped; this paragraph and the
one above form the message's leading comment.

# Fields
- `name::String`: Human-readable name of the library branch.
- `books::Vector{Book}`: Every book currently in the catalog, in no particular order.
- `members_by_id::OrderedDict{String,Member}`: Registered members, keyed by their member id.
"""
struct Library <: PB.AbstractProtoBufMessage
    "Human-readable name of the library branch."
    name::String
    "Every book currently in the catalog, in no particular order."
    books::Vector{Book}
    "Registered members, keyed by their member id."
    members_by_id::OrderedDict{String,Member}
    var"#unknown_fields"::Vector{UInt8}
end
function PB.field_numbers(::Type{Library})
    return (;name = 1, books = 2, members_by_id = 3)
end
function PB.json_field_names(::Type{Library})
    return (;name = "name", books = "books", members_by_id = "membersById")
end
PB.register_message_type("library.Library", Library)

function PB._decode(_d::PB.AbstractProtoDecoder, ::Type{<:Library}, _endpos::Int=0, _group::Bool=false)
    name = ""
    books = PB.BufferedVector{Book}()
    members_by_id = OrderedDict{String,Member}()
    _unknown_fields = UInt8[]
    while !PB.message_done(_d, _endpos, _group)
        field_number, wire_type = PB.decode_tag(_d)
        if field_number == 1
            name = PB._decode(_d, String)
        elseif field_number == 2
            PB._decode!(_d, books)
        elseif field_number == 3
            PB._decode!(_d, members_by_id)
        else
            PB._skip_and_capture!(_unknown_fields, _d, field_number, wire_type)
        end
    end
    return Library(name, books[], members_by_id, _unknown_fields)
end

function PB._encode(_e::PB.AbstractProtoEncoder, _x::Library)
    initpos = position(_e.io)
    !isempty(_x.name) && PB._encode(_e, 1, _x.name)
    !isempty(_x.books) && PB._encode(_e, 2, _x.books)
    !isempty(_x.members_by_id) && PB._encode(_e, 3, _x.members_by_id)
    if !isempty(_x.var"#unknown_fields")
        write(_e.io, _x.var"#unknown_fields")
    end
    return position(_e.io) - initpos
end
function PB._encoded_size(_x::Library)
    encoded_size = 0
    !isempty(_x.name) && (encoded_size += PB._encoded_size(_x.name, 1))
    !isempty(_x.books) && (encoded_size += PB._encoded_size(_x.books, 2))
    !isempty(_x.members_by_id) && (encoded_size += PB._encoded_size(_x.members_by_id, 3))
    encoded_size += length(_x.var"#unknown_fields")
    return encoded_size
end
@batteries Library typesalt=0x0c74f4dd452b2c69 kwconstructor=true kwshow=true
function PB.StructHelpers.default_keywords(::Type{Library})
    return (;name = "", books = Vector{Book}(), members_by_id = OrderedDict{String,Member}(), var"#unknown_fields" = UInt8[])
end


#! format: on
