# Generated by ProtocGen. Do not edit.
# source: palette.proto (proto3 syntax)
#! format: off

import ProtocGen as PB
using ProtocGen: OneOf, OrderedDict
using ProtocGen: encode, decode, encode_json, decode_json
using ProtocGen: enum_metadata
using ProtocGen.EnumX: @enumx
using ProtocGen.StructHelpers: @batteries, @enumbatteries

export Color, enum_metadata

@enumx Color UNSPECIFIED=0 RED=1 GREEN=2 BLUE=3
@enumbatteries Color.T typesalt=0x35e91011ec947459
PB._enum_proto_prefix(::Type{Color.T}) = "COLOR_"
function PB.enum_metadata(x::Color.T)::NamedTuple{(:hex, :sort_order, :hidden), Tuple{String, Int32, Bool}}
    if x == Color.UNSPECIFIED
        return (hex = "", sort_order = zero(Int32), hidden = false)
    elseif x == Color.RED
        return (hex = "ff0000", sort_order = Int32(1), hidden = false)
    elseif x == Color.GREEN
        return (hex = "00ff00", sort_order = Int32(2), hidden = false)
    elseif x == Color.BLUE
        return (hex = "0000ff", sort_order = Int32(3), hidden = true)
    else
        error("enum_metadata: unreachable enum variant: $x")
    end
end


#! format: on
